name: ci
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

env:
  APP_NAME: ecs-demo-app1
  APP_IMAGE: myspotontheweb/ecs-demo-app1
  GITOPS_REPO: myspotontheweb/ecs-workloads

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{env.APP_IMAGE}}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=sha

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  deploy-dev:
    if: contains(github.ref, 'heads')
    runs-on: ubuntu-latest
    needs:
      - build
    steps:

      - uses: actions/checkout@v2
        with:
          repository: ${{env.GITOPS_REPO}}
          token: ${{secrets.REPO_TOKEN}}

      - name: Install dependencies
        run: sudo apt-get install -y yq moreutils

      - name: Update image field
        run: jq ".containerDefinitions[0].image=\"$APP_IMAGE:sha-$(git rev-parse --short $GITHUB_SHA)\"" apps/service-alpha/dev.json | sponge apps/service-alpha/dev.json

      - name: Commit changes
        run: |
          git config user.email "gitops@myspotontheweb.com"
          git config user.name "gitops"
          git commit -am "Gitops update to $APP_NAME"
          git pull --rebase
          git push


  deploy-release:
    if: contains(github.ref, 'tags')
    runs-on: ubuntu-latest
    needs:
      - build
    steps:

      - uses: actions/checkout@v2
        with:
          repository: ${{env.GITOPS_REPO}}
          token: ${{secrets.REPO_TOKEN}}

      - name: Install dependencies
        run: sudo apt-get install -y yq moreutils

      - name: Update image field
        run: jq ".containerDefinitions[0].image=\"$APP_IMAGE:${GITHUB_REF#refs/*/}\"" apps/service-alpha/test.json | sponge apps/service-alpha/test.json

      - name: Commit changes
        run: |
          git config user.email "gitops@myspotontheweb.com"
          git config user.name "gitops"
          git commit -am "Gitops update to $APP_NAME"
          git pull --rebase
          git push
